FROM python:3.10-slim

WORKDIR /app

COPY ./backend /app

RUN apt-get update && \
    apt-get install -y build-essential dssp && \
    pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
EXPOSE 8000